version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  allow:
  - dependency-name: "k8s.io/.*"
  - dependency-name: "sigs.k8s.io/.*"
  - dependency-name: "golang.org/x/.*"
  - dependency-name: "github.com/go-jose/.*"
  - dependency-name: "github.com/coreos/go-oidc"
  - dependency-name: "github.com/coreos/go-oidc/v3"
  - dependency-name: "github.com/onsi/.*"
  - dependency-name: "github.com/prometheus/.*"
  labels:
  - kind/enhancement
- package-ecosystem: docker
  directories:
  - /
  schedule:
    interval: daily
  labels:
  - kind/enhancement
