version: "2"
run:
  concurrency: 4
linters:
  enable:
    - gocritic
    - revive
  settings:
    revive:
      rules:
      - name: dot-imports
        disabled: true
      - name: indent-error-flow
        disabled: true
      - name: package-comments
        disabled: true
