---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - authentication.gardener.cloud
  resources:
  - openidconnects
  verbs:
  - get
  - list
  - watch
