# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: A Helm chart to deploy the oidc-webhook-authenticator application related resources
name: application
version: 0.1.0
