# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: A Helm chart to deploy the oidc-webhook-authenticator runtime related resources
name: runtime
version: 0.1.0
